services:
  # ==========================================
  # 1. API (Sua Aplicação Principal)
  # ==========================================
  - type: web
    name: fivemlet-api
    runtime: docker
    dockerfilePath: ./Dockerfile # Verifique se o nome do arquivo é exatamente "dockerfile" (minúsculo) ou "Dockerfile"
    plan: free
    envVars:
      - key: HF_TOKEN
        sync: false # Lembre-se de adicionar isso no painel do Render!
      - key: HF_REPO_ID
        value: seu-usuario/seu-modelo

  # ==========================================
  # 2. Prometheus (Coletor de Métricas)
  # ==========================================
  - type: pserv # Private Service (Só acessível internamente pelo Grafana)
    name: prometheus-server
    runtime: docker
    rootDir: monitoring/prometheus
    # DISK REMOVIDO PARA RODAR NO PLANO FREE
    plan: free
    envVars:
      - key: PORT
        value: 9090

  # ==========================================
  # 3. Grafana (Dashboard Visual)
  # ==========================================
  - type: web
    name: grafana-server
    runtime: docker
    rootDir: monitoring/grafana
    # DISK REMOVIDO PARA RODAR NO PLANO FREE
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: GF_SECURITY_ADMIN_PASSWORD
        generateValue: true
      - key: PROMETHEUS_URL
        value: http://prometheus-server:9090