apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app: grafana
data:
  datasource.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false

  dashboard-provider.yml: |-
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards

  basic_metrics.json: |-
    {
      "annotations": {"list": []},
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": "Prometheus",
          "fieldConfig": {"defaults": {}, "overrides": []},
          "gridPos": {"h": 8, "w": 24, "x": 0, "y": 0},
          "id": 1,
          "options": {},
          "targets": [
            {"expr": "sum(rate(http_requests_total[1m])) by (endpoint)", "legendFormat": "{{endpoint}}", "refId": "A"}
          ],
          "title": "Requests per second (by endpoint)",
          "type": "timeseries"
        },
        {
          "datasource": "Prometheus",
          "fieldConfig": {"defaults": {}, "overrides": []},
          "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8},
          "id": 2,
          "options": {},
          "targets": [
            {"expr": "histogram_quantile(0.95, sum(rate(http_request_latency_seconds_bucket[5m])) by (le))", "refId": "A"}
          ],
          "title": "95th percentile request latency (s)",
          "type": "timeseries"
        }
      ],
      "refresh": "10s",
      "schemaVersion": 32,
      "style": "dark",
      "tags": [],
      "templating": {"list": []},
      "time": {"from": "now-1h", "to": "now"},
      "timepicker": {},
      "timezone": "browser",
      "title": "Basic App Metrics",
      "uid": "basic-app-metrics"
    }
